# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388be9f599561d094f682714dbaa637a6b8bcc9c97e5c63335de5498761ad7183daad3908fff634da3c1e6b113cc0f4c792d00a6782ec996c8bb2faa6a2792f9

test:
  secret_key_base: a8400fe6c5bf532f61387f8eec1bd74e3cc4fe32342b59acae9498806a70857021ec97190f84c8e5623fe48a4e94599901905919eefec07ebe57de2dfd0a88dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
